"""GENERERAD av scripts/gen_agentur.py — redigera inte för hand."""

# Modell-tier för AKTIVA agenter (router-override).
MODEL_TIER = {
    'agile-coach': 'claude-sonnet-4-6',
    'backend-developer': 'claude-sonnet-4-6',
    'chief-of-staff': 'claude-sonnet-4-6',
    'communications-lead': 'claude-sonnet-4-6',
    'coo': 'claude-opus-4-8',
    'cto': 'claude-opus-4-8',
    'devops-engineer': 'claude-haiku-4-5',
    'finance-lead': 'claude-haiku-4-5',
    'frontend-developer': 'claude-sonnet-4-6',
    'fullstack-developer': 'claude-sonnet-4-6',
    'integration-developer': 'claude-sonnet-4-6',
    'learning-developer': 'claude-sonnet-4-6',
    'maintenance-engineer': 'claude-sonnet-4-6',
    'operations-lead': 'claude-sonnet-4-6',
    'org-architect': 'claude-sonnet-4-6',
    'people-lead': 'claude-sonnet-4-6',
    'platform-engineer': 'claude-sonnet-4-6',
    'platform-lead': 'claude-sonnet-4-6',
    'product-lead': 'claude-haiku-4-5',
    'program-lead': 'claude-sonnet-4-6',
    'qa-lead': 'claude-sonnet-4-6',
    'research-lead': 'claude-sonnet-4-6',
    'session-coordinator': 'claude-haiku-4-5',
    'situation-analyst': 'claude-haiku-4-5',
    'solution-architect': 'claude-sonnet-4-6',
    'technical-writer': 'claude-sonnet-4-6',
    'terminal-developer': 'claude-sonnet-4-6',
}

# Avdelning per slug (alla roller, aktiva + skal).
DEPARTMENT = {
    'agile-coach': 'Program',
    'backend-developer': 'Engineering',
    'backend-developer-2': 'Engineering',
    'backend-developer-3': 'Engineering',
    'backend-developer-4': 'Engineering',
    'backend-lead': 'Engineering',
    'build-engineer': 'Platform',
    'chief-of-staff': 'Leadership',
    'communications-lead': 'Communications',
    'community-ansvarig': 'Communications',
    'competitor-analyst': 'R&D',
    'controller': 'Finance',
    'coo': 'Leadership',
    'cpo': 'Leadership',
    'cto': 'Leadership',
    'data-engineer': 'Engineering',
    'data-engineer-2': 'Engineering',
    'datavetare': 'R&D',
    'delivery-lead': 'Program',
    'devex-engineer': 'Platform',
    'devops-engineer': 'Engineering',
    'devops-engineer-2': 'Platform',
    'devrel-ansvarig': 'Communications',
    'faktureringsansvarig': 'Finance',
    'finance-lead': 'Finance',
    'finops-analyst': 'Finance',
    'frontend-developer': 'Engineering',
    'frontend-developer-2': 'Engineering',
    'frontend-developer-3': 'Engineering',
    'frontend-lead': 'Engineering',
    'fullstack-developer': 'Engineering',
    'fullstack-developer-2': 'Engineering',
    'incident-lead': 'Operations',
    'inkop': 'Finance',
    'innehallsskapare': 'Communications',
    'innovation-lead': 'R&D',
    'integration-developer': 'Engineering',
    'integration-developer-2': 'Engineering',
    'interaktionsdesigner': 'Product',
    'kulturansvarig': 'People',
    'learning-developer': 'People',
    'learning-developer-2': 'People',
    'maintenance-engineer': 'Operations',
    'maintenance-engineer-2': 'Operations',
    'market-analyst': 'R&D',
    'marketer': 'Communications',
    'monitoring-analyst': 'Operations',
    'operations-lead': 'Operations',
    'org-architect': 'People',
    'people-lead': 'People',
    'platform-engineer': 'Platform',
    'platform-engineer-2': 'Platform',
    'platform-lead': 'Platform',
    'product-analyst': 'Product',
    'product-lead': 'Product',
    'product-lead-core': 'Product',
    'product-lead-dashboard': 'Product',
    'product-lead-mcp': 'Product',
    'product-lead-tui': 'Product',
    'product-ops': 'Product',
    'program-lead': 'Program',
    'prototypare': 'R&D',
    'qa-lead': 'Engineering',
    'rekryterare': 'People',
    'rekryterare-2': 'People',
    'release-coordinator': 'Program',
    'research-lead': 'R&D',
    'scrum-master': 'Program',
    'scrum-master-2': 'Program',
    'session-coordinator': 'Program',
    'session-coordinator-2': 'Program',
    'situation-analyst': 'Operations',
    'solution-architect': 'Product',
    'sre-engineer': 'Operations',
    'sre-engineer-2': 'Operations',
    'strategy-lead': 'Leadership',
    'technical-writer': 'Communications',
    'technical-writer-2': 'Communications',
    'teknikspanare': 'R&D',
    'terminal-developer': 'Engineering',
    'terminal-developer-2': 'Engineering',
    'testautomatiserare': 'Engineering',
    'testautomatiserare-2': 'Engineering',
    'testautomatiserare-3': 'Engineering',
    'ux-designer': 'Product',
    'ux-lead': 'Product',
    'ux-researcher': 'Product',
    'web-researcher': 'R&D',
}

# Full roster (org-registret).
ROSTER = [
    {'slug': 'community-ansvarig', 'title': 'Community-ansvarig', 'department': 'Communications', 'sub_department': 'DevRel', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devrel-ansvarig', 'title': 'DevRel-ansvarig', 'department': 'Communications', 'sub_department': 'DevRel', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'communications-lead', 'title': 'Kommunikationschef', 'department': 'Communications', 'sub_department': 'Docs', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'technical-writer', 'title': 'Teknisk skribent', 'department': 'Communications', 'sub_department': 'Docs', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'technical-writer-2', 'title': 'Teknisk skribent', 'department': 'Communications', 'sub_department': 'Docs', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'innehallsskapare', 'title': 'Innehållsskapare', 'department': 'Communications', 'sub_department': 'Marketing', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'marketer', 'title': 'Marknadsförare', 'department': 'Communications', 'sub_department': 'Marketing', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'backend-developer', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'squad': 'Integrationer', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'backend-developer-2', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-developer-3', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-developer-4', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-lead', 'title': 'Backend-lead', 'department': 'Engineering', 'sub_department': 'Backend', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'data-engineer', 'title': 'Data-ingenjör', 'department': 'Engineering', 'sub_department': 'Data', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'data-engineer-2', 'title': 'Data-ingenjör', 'department': 'Engineering', 'sub_department': 'Data', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devops-engineer', 'title': 'DevOps-ingenjör', 'department': 'Engineering', 'sub_department': 'DevOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'frontend-developer', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'Insikter', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'frontend-developer-2', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'frontend-developer-3', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'frontend-lead', 'title': 'Frontend-lead', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'terminal-developer', 'title': 'Terminal-UI-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'Överblick', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'terminal-developer-2', 'title': 'Terminal-UI-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'squad': 'Överblick', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'fullstack-developer', 'title': 'Fullstack-utvecklare', 'department': 'Engineering', 'sub_department': 'Fullstack', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'fullstack-developer-2', 'title': 'Fullstack-utvecklare', 'department': 'Engineering', 'sub_department': 'Fullstack', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'integration-developer', 'title': 'Integrationsutvecklare', 'department': 'Engineering', 'sub_department': 'Integrations', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'integration-developer-2', 'title': 'Integrationsutvecklare', 'department': 'Engineering', 'sub_department': 'Integrations', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'qa-lead', 'title': 'QA-lead', 'department': 'Engineering', 'sub_department': 'QA', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'testautomatiserare', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'testautomatiserare-2', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'testautomatiserare-3', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'controller', 'title': 'Controller', 'department': 'Finance', 'sub_department': 'Controlling', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'finance-lead', 'title': 'Ekonomichef (CFO)', 'department': 'Finance', 'sub_department': 'Controlling', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': True, 'active': True},
    {'slug': 'faktureringsansvarig', 'title': 'Faktureringsansvarig', 'department': 'Finance', 'sub_department': 'FinOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'finops-analyst', 'title': 'FinOps-analytiker', 'department': 'Finance', 'sub_department': 'FinOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'inkop', 'title': 'Inköpsansvarig', 'department': 'Finance', 'sub_department': 'FinOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'chief-of-staff', 'title': 'Stabschef (Chief of Staff)', 'department': 'Leadership', 'sub_department': 'Exec', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'coo', 'title': 'Operativ chef (COO)', 'department': 'Leadership', 'sub_department': 'Exec', 'squad': 'null', 'model': 'claude-opus-4-8', 'lead': True, 'active': True},
    {'slug': 'cpo', 'title': 'Produktdirektör (CPO)', 'department': 'Leadership', 'sub_department': 'Exec', 'squad': 'null', 'model': 'claude-opus-4-8', 'lead': True, 'active': False},
    {'slug': 'cto', 'title': 'Teknisk direktör (CTO)', 'department': 'Leadership', 'sub_department': 'Exec', 'squad': 'null', 'model': 'claude-opus-4-8', 'lead': True, 'active': True},
    {'slug': 'strategy-lead', 'title': 'Strategichef', 'department': 'Leadership', 'sub_department': 'Exec', 'squad': 'null', 'model': 'claude-opus-4-8', 'lead': True, 'active': False},
    {'slug': 'incident-lead', 'title': 'Incidentledare', 'department': 'Operations', 'sub_department': 'Incident', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'maintenance-engineer', 'title': 'Underhållsingenjör', 'department': 'Operations', 'sub_department': 'Maintenance', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'maintenance-engineer-2', 'title': 'Underhållsingenjör', 'department': 'Operations', 'sub_department': 'Maintenance', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'monitoring-analyst', 'title': 'Övervakningsanalytiker', 'department': 'Operations', 'sub_department': 'Monitoring', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'situation-analyst', 'title': 'Lägesanalytiker', 'department': 'Operations', 'sub_department': 'Monitoring', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'operations-lead', 'title': 'Driftchef', 'department': 'Operations', 'sub_department': 'SRE', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'sre-engineer', 'title': 'SRE-ingenjör', 'department': 'Operations', 'sub_department': 'SRE', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'sre-engineer-2', 'title': 'SRE-ingenjör', 'department': 'Operations', 'sub_department': 'SRE', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'kulturansvarig', 'title': 'Kulturansvarig', 'department': 'People', 'sub_department': 'Culture', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'learning-developer', 'title': 'Kompetensutvecklare (L&D)', 'department': 'People', 'sub_department': 'L&D', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'learning-developer-2', 'title': 'Kompetensutvecklare', 'department': 'People', 'sub_department': 'L&D', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'org-architect', 'title': 'Organisationsarkitekt', 'department': 'People', 'sub_department': 'Org Design', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'people-lead', 'title': 'HR-chef (CHRO)', 'department': 'People', 'sub_department': 'Talent', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'rekryterare', 'title': 'Rekryterare', 'department': 'People', 'sub_department': 'Talent', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'rekryterare-2', 'title': 'Rekryterare', 'department': 'People', 'sub_department': 'Talent', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'build-engineer', 'title': 'Build-ingenjör', 'department': 'Platform', 'sub_department': 'DevEx', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devex-engineer', 'title': 'Developer-Experience-ingenjör', 'department': 'Platform', 'sub_department': 'DevEx', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'devops-engineer-2', 'title': 'DevOps-ingenjör', 'department': 'Platform', 'sub_department': 'DevOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'platform-engineer', 'title': 'Plattformsingenjör', 'department': 'Platform', 'sub_department': 'Infra', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'platform-engineer-2', 'title': 'Plattformsingenjör', 'department': 'Platform', 'sub_department': 'Infra', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'platform-lead', 'title': 'Plattformschef', 'department': 'Platform', 'sub_department': 'Infra', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'solution-architect', 'title': 'Lösningsarkitekt', 'department': 'Product', 'sub_department': 'Arkitektur', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'interaktionsdesigner', 'title': 'Interaktionsdesigner', 'department': 'Product', 'sub_department': 'Design', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'ux-designer', 'title': 'UX-designer', 'department': 'Product', 'sub_department': 'Design', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'ux-lead', 'title': 'UX-lead', 'department': 'Product', 'sub_department': 'Design', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'ux-researcher', 'title': 'UX-researcher', 'department': 'Product', 'sub_department': 'Design', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-lead', 'title': 'Produktchef', 'department': 'Product', 'sub_department': 'PM', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': True, 'active': True},
    {'slug': 'product-lead-core', 'title': 'Produktledare CNS-core', 'department': 'Product', 'sub_department': 'PM', 'squad': 'Modellering', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-lead-dashboard', 'title': 'Produktledare Dashboard', 'department': 'Product', 'sub_department': 'PM', 'squad': 'Insikter', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-lead-mcp', 'title': 'Produktledare MCP-plattform', 'department': 'Product', 'sub_department': 'PM', 'squad': 'Integrationer', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-lead-tui', 'title': 'Produktledare TUI', 'department': 'Product', 'sub_department': 'PM', 'squad': 'Överblick', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-analyst', 'title': 'Produktanalytiker', 'department': 'Product', 'sub_department': 'ProductOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'product-ops', 'title': 'Product Ops', 'department': 'Product', 'sub_department': 'ProductOps', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'agile-coach', 'title': 'Agile Coach', 'department': 'Program', 'sub_department': 'Coaching', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'session-coordinator', 'title': 'Sessionskoordinator', 'department': 'Program', 'sub_department': 'Coordination', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'session-coordinator-2', 'title': 'Sessionskoordinator', 'department': 'Program', 'sub_department': 'Coordination', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'program-lead', 'title': 'Programledare', 'department': 'Program', 'sub_department': 'Delivery', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'scrum-master', 'title': 'Scrum Master', 'department': 'Program', 'sub_department': 'Delivery', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'scrum-master-2', 'title': 'Scrum Master', 'department': 'Program', 'sub_department': 'Delivery', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'delivery-lead', 'title': 'Leveranschef', 'department': 'Program', 'sub_department': 'Release', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'release-coordinator', 'title': 'Release-koordinator', 'department': 'Program', 'sub_department': 'Release', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'datavetare', 'title': 'Datavetare', 'department': 'R&D', 'sub_department': 'Innovation', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'innovation-lead', 'title': 'Innovationsledare', 'department': 'R&D', 'sub_department': 'Innovation', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'prototypare', 'title': 'Prototypare', 'department': 'R&D', 'sub_department': 'Innovation', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'competitor-analyst', 'title': 'Konkurrentanalytiker', 'department': 'R&D', 'sub_department': 'Research', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'market-analyst', 'title': 'Marknadsanalytiker', 'department': 'R&D', 'sub_department': 'Research', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'research-lead', 'title': 'Forskningsledare', 'department': 'R&D', 'sub_department': 'Research', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'teknikspanare', 'title': 'Teknikspanare', 'department': 'R&D', 'sub_department': 'Research', 'squad': 'null', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'web-researcher', 'title': 'Webbresearcher', 'department': 'R&D', 'sub_department': 'Research', 'squad': 'null', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
]

# Tvärfunktionella squads (mission-team) -> medlems-slugs.
SQUADS = {
    'Insikter': ['frontend-developer', 'product-lead-dashboard'],
    'Integrationer': ['backend-developer', 'product-lead-mcp'],
    'Modellering': ['product-lead-core'],
    'Överblick': ['terminal-developer', 'terminal-developer-2', 'product-lead-tui'],
}
