"""Export node data to JSON format."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from scripts.md_parser import read_all_nodes

logger = logging.getLogger(__name__)

EXPORTS_DIR = Path(__file__).resolve().parent.parent / "exports"
_AGENTS_FILE = EXPORTS_DIR / "agents.json"


def _extract_audience(section_text: str, label: str) -> str:
    """Extract a labelled audience from the Target Audience section."""
    for line in section_text.splitlines():
        if label in line:
            return line.split(":", 1)[-1].strip().strip("*")
    return ""


def _list_items(section_text: str) -> list[str]:
    """Return bullet-list items as a list of strings."""
    items = []
    for line in section_text.splitlines():
        line = line.strip()
        if line.startswith("- "):
            items.append(line[2:].strip())
    return items


def _top_risk(section_text: str) -> str:
    """Return the first risk line from Risk Assessment."""
    for line in section_text.splitlines():
        line = line.strip()
        if line.startswith("- "):
            return line[2:].strip()
    return ""


def _load_agents() -> list[dict]:
    """Load agents from exports/agents.json (generated by gen_agentur.py, Plan A projection).

    Returns empty list if the file does not exist yet.
    Never reads .claude/ directly — Plan A/B-väggen upprätthålls genom att bara
    läsa den förgenerade artefakten, inte källan.
    """
    if not _AGENTS_FILE.exists():
        return []
    data = json.loads(_AGENTS_FILE.read_text(encoding="utf-8"))
    return data.get("agents", [])


def _derive_ownership_edges(node_list: list[dict]) -> list[dict]:
    """Derive owns/contributes_to edges from node owner_agent/contributing_agents fields."""
    edges: list[dict] = []
    for node in node_list:
        slug = node.get("slug", "")
        owner = node.get("owner_agent", "")
        if owner:
            edges.append({"from": owner, "to": slug, "type": "owns"})
        for agent in node.get("contributing_agents") or []:
            if agent:
                edges.append({"from": agent, "to": slug, "type": "contributes_to"})
    return edges


def _safe_list_issues(token: Optional[str] = None) -> list[dict]:
    """Hämta alla issues en gång; [] utan credentials/nät (lokal export funkar ändå)."""
    try:
        from scripts.issues_client import list_issues  # noqa: PLC0415
    except ImportError:
        return []
    try:
        return list_issues(state="all", token=token)
    except Exception:
        logger.debug("_safe_list_issues: GitHub call failed", exc_info=True)
        return []


def _node_health(slug: str, issues: list[dict], systems: Optional[dict]) -> dict:
    """Per-nod hälso-scorecard; {} om något fallerar (export får aldrig brytas)."""
    if not slug:
        return {}
    try:
        from scripts.health import health_for_node
        return health_for_node(slug, issues=issues, systems=systems)
    except Exception:
        logger.debug("_node_health failed for %s", slug, exc_info=True)
        return {}


def _derive_work_edges(token: Optional[str] = None, issues: Optional[list[dict]] = None) -> list[dict]:
    """Derive targets/addresses/assigned_to edges via issues_client.

    Requires GITHUB_REPO + token (or CNS_GITHUB_TOKEN env var).
    Returns [] when credentials are absent or when the GitHub call fails so that
    export_json still works locally without network access. ``issues`` may be
    passed in to reuse a single fetch (health + edges share it).
    """
    try:
        from scripts.issues_client import list_milestones  # noqa: PLC0415
    except ImportError:
        return []

    if issues is None:
        issues = _safe_list_issues(token=token)

    edges: list[dict] = []
    quest_nodes: dict[int, set[str]] = {}

    for issue in issues:
        number = issue.get("number")
        slug = issue.get("node_slug")
        if number and slug:
            edges.append({"from": f"issue:{number}", "to": slug, "type": "addresses"})
            quest_num = issue.get("quest")
            if quest_num:
                quest_nodes.setdefault(quest_num, set()).add(slug)
        for assignee in issue.get("assignees") or []:
            if number and assignee:
                edges.append({"from": f"issue:{number}", "to": assignee, "type": "assigned_to"})

    try:
        milestones = list_milestones(state="all", token=token)
    except Exception:
        logger.debug("_derive_work_edges: milestones call failed", exc_info=True)
        milestones = []

    for ms in milestones:
        ms_num = ms.get("number")
        if ms_num and ms_num in quest_nodes:
            for slug in quest_nodes[ms_num]:
                edges.append({"from": f"quest:{ms_num}", "to": slug, "type": "targets"})

    return edges


def export_json(
    output_path: Optional[Path] = None,
    token: Optional[str] = None,
) -> Path:
    """Generate exports/nodes.json (v3.0) from all node files.

    Adds three top-level keys (additive, v2.0 consumers unaffected):
      - agents: list from exports/agents.json
      - edges: ownership + work-item kanter
    New per-node fields: type, domain, owner_agent, contributing_agents (all optional,
    empty-string/list fallback so dashboarden aldrig bryts av en gammal nod).

    Returns the path to the generated file.
    """
    if output_path is None:
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        output_path = EXPORTS_DIR / "nodes.json"
    else:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

    nodes = read_all_nodes()
    agents = _load_agents()

    # Härledd verklighets-status per nod (true/stale/aspirational/grouping) — INTE
    # handtaggat; klassas ur repo-backing + nodens summary (derive_catalog, Del A).
    try:
        from scripts.derive_catalog import (
            classify_catalog, load_current_catalog, repo_file_stems,
        )
        reality = classify_catalog(load_current_catalog(), file_stems=repo_file_stems())
    except Exception:
        reality = {}

    # Härledd hälsa per nod (roll-up av öppna issues + strukturell katalog-check).
    # Ett enda issue-fetch delas med work-edges nedan; tomt = degraderar till {}.
    issues = _safe_list_issues(token=token)
    try:
        from scripts.catalog import load_catalog
        _systems = load_catalog()
    except Exception:
        _systems = None

    node_list = []
    for meta, sections in nodes:
        node_list.append({
            "slug": meta.get("slug", ""),
            "title": meta.get("title", ""),
            # Node-model fields (always exported, empty string/list if absent)
            "kind": meta.get("kind", ""),
            "stage": meta.get("stage", ""),
            "part_of": meta.get("part_of", ""),
            "feeds": meta.get("feeds", []),
            "depends_on": meta.get("depends_on", []),
            "layer": meta.get("layer", ""),
            "pipeline": meta.get("pipeline", ""),
            # v3.0 node-model fields (optional; empty fallback — dashboarden fallbackar)
            "type": meta.get("type", ""),
            "domain": meta.get("domain", ""),
            # Härlett: en produkt = system med egen venture-domän (≠ cortxt). Backenden
            # äger klassningen så frontenden slipper hårdkoda venture-listan. Additivt.
            "is_product": bool(meta.get("domain")) and meta.get("domain") != "cortxt",
            # Härledd verklighets-status (true|stale|aspirational|grouping), tom om okänd.
            "reality_status": reality.get(meta.get("slug", ""), ("", ""))[0],
            # Härledd hälso-scorecard {level, checks:[...]} — additiv; {} utan GitHub.
            "health": _node_health(meta.get("slug", ""), issues, _systems),
            "owner_agent": meta.get("owner_agent", ""),
            "contributing_agents": meta.get("contributing_agents") or [],
            # External integrations (#77): deploy (drift) vs sources (källor). Additive;
            # {} fallback so the dashboard never breaks on systems without it.
            "integrations": meta.get("integrations") or {},
            # Legacy product fields (kept for backward compatibility)
            "status": meta.get("status", ""),
            "mvp_stage": meta.get("mvp_stage", ""),
            "cost_sek": meta.get("cost_sek", 0),
            "value_sek": meta.get("value_sek", 0),
            "roi_percent": meta.get("roi_percent", 0),
            "tags": meta.get("tags", []),
            "created": str(meta.get("created", "")),
            "updated": str(meta.get("updated", "")),
            "summary": meta.get("summary", ""),
            "family": meta.get("family", ""),
            "url_live": meta.get("url_live", ""),
            "url_repo": meta.get("url_repo", ""),
            "current_slice": meta.get("current_slice", ""),
            # Product sections (only meaningful for legacy product nodes,
            # component/system/framework nodes use different sections)
            "problem": sections.get("Problem", "").strip(),
            "solution": sections.get("Solution", "").strip(),
            "primary_audience": _extract_audience(sections.get("Target Audience", ""), "Primary"),
            "assumptions": _list_items(sections.get("Assumptions to Validate", "")),
            "mvp_steps": _list_items(sections.get("MVP Steps", "")),
            "top_risk": _top_risk(sections.get("Risk Assessment", "")),
            # Component/system/framework sections
            "syfte": sections.get("Syfte", sections.get("Syfte/mål", sections.get("Vision", ""))).strip(),
        })

    edges = _derive_ownership_edges(node_list)
    edges += _derive_work_edges(token=token, issues=issues)

    payload = {
        "exported_at": datetime.now().isoformat(),
        "version": "3.1",
        "nodes": node_list,
        "agents": agents,
        "edges": edges,
    }

    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    return output_path
