"""GENERERAD av scripts/gen_agentur.py — redigera inte för hand."""

# Modell-tier för AKTIVA agenter (router-override).
MODEL_TIER = {
    'backend-utvecklare': 'claude-sonnet-4-6',
    'devops-ingenjor': 'claude-haiku-4-5',
    'ekonomichef': 'claude-haiku-4-5',
    'forskningsledare': 'claude-sonnet-4-6',
    'frontend-utvecklare': 'claude-sonnet-4-6',
    'fullstack-utvecklare': 'claude-sonnet-4-6',
    'hr-chef': 'claude-sonnet-4-6',
    'kompetensutvecklare': 'claude-sonnet-4-6',
    'lagesanalytiker': 'claude-haiku-4-5',
    'losningsarkitekt': 'claude-sonnet-4-6',
    'operativ-chef': 'claude-opus-4-8',
    'plattformsingenjor': 'claude-sonnet-4-6',
    'produktchef': 'claude-haiku-4-5',
    'programledare': 'claude-sonnet-4-6',
    'sessionskoordinator': 'claude-haiku-4-5',
    'teknisk-skribent': 'claude-sonnet-4-6',
    'terminal-utvecklare': 'claude-sonnet-4-6',
    'underhallsingenjor': 'claude-sonnet-4-6',
}

# Avdelning per slug (alla roller, aktiva + skal).
DEPARTMENT = {
    'backend-lead': 'Engineering',
    'backend-utvecklare': 'Engineering',
    'backend-utvecklare-2': 'Engineering',
    'backend-utvecklare-3': 'Engineering',
    'backend-utvecklare-4': 'Engineering',
    'build-ingenjor': 'Platform',
    'community-ansvarig': 'Kommunikation',
    'controller': 'Ekonomi',
    'data-ingenjor': 'Engineering',
    'data-ingenjor-2': 'Engineering',
    'datavetare': 'R&D',
    'devex-ingenjor': 'Platform',
    'devops-ingenjor': 'Engineering',
    'devops-ingenjor-2': 'Platform',
    'devrel-ansvarig': 'Kommunikation',
    'driftchef': 'Drift',
    'ekonomichef': 'Ekonomi',
    'faktureringsansvarig': 'Ekonomi',
    'finops-analytiker': 'Ekonomi',
    'forskningsledare': 'R&D',
    'frontend-lead': 'Engineering',
    'frontend-utvecklare': 'Engineering',
    'frontend-utvecklare-2': 'Engineering',
    'frontend-utvecklare-3': 'Engineering',
    'fullstack-utvecklare': 'Engineering',
    'fullstack-utvecklare-2': 'Engineering',
    'hr-chef': 'People',
    'incidentledare': 'Drift',
    'inkop': 'Ekonomi',
    'innehallsskapare': 'Kommunikation',
    'innovationsledare': 'R&D',
    'integrationsutvecklare': 'Engineering',
    'integrationsutvecklare-2': 'Engineering',
    'interaktionsdesigner': 'Produkt',
    'kommunikationschef': 'Kommunikation',
    'kompetensutvecklare': 'People',
    'kompetensutvecklare-2': 'People',
    'konkurrentanalytiker': 'R&D',
    'kulturansvarig': 'People',
    'lagesanalytiker': 'Drift',
    'leveranschef': 'Program',
    'losningsarkitekt': 'Produkt',
    'marknadsanalytiker': 'R&D',
    'marknadsforare': 'Kommunikation',
    'operativ-chef': 'Ledning',
    'overvakningsanalytiker': 'Drift',
    'plattformschef': 'Platform',
    'plattformsingenjor': 'Platform',
    'plattformsingenjor-2': 'Platform',
    'product-ops': 'Produkt',
    'produktanalytiker': 'Produkt',
    'produktchef': 'Produkt',
    'produktdirektor': 'Ledning',
    'produktledare-core': 'Produkt',
    'produktledare-dashboard': 'Produkt',
    'produktledare-mcp': 'Produkt',
    'produktledare-tui': 'Produkt',
    'programledare': 'Program',
    'prototypare': 'R&D',
    'qa-lead': 'Engineering',
    'rekryterare': 'People',
    'rekryterare-2': 'People',
    'release-koordinator': 'Program',
    'scrum-master': 'Program',
    'scrum-master-2': 'Program',
    'sessionskoordinator': 'Program',
    'sessionskoordinator-2': 'Program',
    'sre-ingenjor': 'Drift',
    'sre-ingenjor-2': 'Drift',
    'stabschef': 'Ledning',
    'strategichef': 'Ledning',
    'teknikspanare': 'R&D',
    'teknisk-direktor': 'Ledning',
    'teknisk-skribent': 'Kommunikation',
    'teknisk-skribent-2': 'Kommunikation',
    'terminal-utvecklare': 'Engineering',
    'terminal-utvecklare-2': 'Engineering',
    'testautomatiserare': 'Engineering',
    'testautomatiserare-2': 'Engineering',
    'testautomatiserare-3': 'Engineering',
    'underhallsingenjor': 'Drift',
    'underhallsingenjor-2': 'Drift',
    'ux-designer': 'Produkt',
    'ux-lead': 'Produkt',
    'ux-researcher': 'Produkt',
    'webbresearcher': 'R&D',
}

# Full roster (org-registret).
ROSTER = [
    {'slug': 'incidentledare', 'title': 'Incidentledare', 'department': 'Drift', 'sub_department': 'Incident', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'underhallsingenjor', 'title': 'Underhållsingenjör', 'department': 'Drift', 'sub_department': 'Maintenance', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'underhallsingenjor-2', 'title': 'Underhållsingenjör', 'department': 'Drift', 'sub_department': 'Maintenance', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'lagesanalytiker', 'title': 'Lägesanalytiker', 'department': 'Drift', 'sub_department': 'Monitoring', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'overvakningsanalytiker', 'title': 'Övervakningsanalytiker', 'department': 'Drift', 'sub_department': 'Monitoring', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'driftchef', 'title': 'Driftchef', 'department': 'Drift', 'sub_department': 'SRE', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'sre-ingenjor', 'title': 'SRE-ingenjör', 'department': 'Drift', 'sub_department': 'SRE', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'sre-ingenjor-2', 'title': 'SRE-ingenjör', 'department': 'Drift', 'sub_department': 'SRE', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'controller', 'title': 'Controller', 'department': 'Ekonomi', 'sub_department': 'Controlling', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'ekonomichef', 'title': 'Ekonomichef (CFO)', 'department': 'Ekonomi', 'sub_department': 'Controlling', 'model': 'claude-haiku-4-5', 'lead': True, 'active': True},
    {'slug': 'faktureringsansvarig', 'title': 'Faktureringsansvarig', 'department': 'Ekonomi', 'sub_department': 'FinOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'finops-analytiker', 'title': 'FinOps-analytiker', 'department': 'Ekonomi', 'sub_department': 'FinOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'inkop', 'title': 'Inköpsansvarig', 'department': 'Ekonomi', 'sub_department': 'FinOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-lead', 'title': 'Backend-lead', 'department': 'Engineering', 'sub_department': 'Backend', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'backend-utvecklare', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'backend-utvecklare-2', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-utvecklare-3', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'backend-utvecklare-4', 'title': 'Backend-utvecklare', 'department': 'Engineering', 'sub_department': 'Backend', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'data-ingenjor', 'title': 'Data-ingenjör', 'department': 'Engineering', 'sub_department': 'Data', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'data-ingenjor-2', 'title': 'Data-ingenjör', 'department': 'Engineering', 'sub_department': 'Data', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devops-ingenjor', 'title': 'DevOps-ingenjör', 'department': 'Engineering', 'sub_department': 'DevOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'frontend-lead', 'title': 'Frontend-lead', 'department': 'Engineering', 'sub_department': 'Frontend', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'frontend-utvecklare', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'frontend-utvecklare-2', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'frontend-utvecklare-3', 'title': 'Frontend-utvecklare', 'department': 'Engineering', 'sub_department': 'Frontend', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'fullstack-utvecklare', 'title': 'Fullstack-utvecklare', 'department': 'Engineering', 'sub_department': 'Fullstack', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'fullstack-utvecklare-2', 'title': 'Fullstack-utvecklare', 'department': 'Engineering', 'sub_department': 'Fullstack', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'integrationsutvecklare', 'title': 'Integrationsutvecklare', 'department': 'Engineering', 'sub_department': 'Integrations', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'integrationsutvecklare-2', 'title': 'Integrationsutvecklare', 'department': 'Engineering', 'sub_department': 'Integrations', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'qa-lead', 'title': 'QA-lead', 'department': 'Engineering', 'sub_department': 'QA', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'testautomatiserare', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'testautomatiserare-2', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'testautomatiserare-3', 'title': 'Testautomatiserare', 'department': 'Engineering', 'sub_department': 'QA', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'terminal-utvecklare', 'title': 'Terminal-UI-utvecklare', 'department': 'Engineering', 'sub_department': 'TUI', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'terminal-utvecklare-2', 'title': 'Terminal-UI-utvecklare', 'department': 'Engineering', 'sub_department': 'TUI', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'community-ansvarig', 'title': 'Community-ansvarig', 'department': 'Kommunikation', 'sub_department': 'DevRel', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devrel-ansvarig', 'title': 'DevRel-ansvarig', 'department': 'Kommunikation', 'sub_department': 'DevRel', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'kommunikationschef', 'title': 'Kommunikationschef', 'department': 'Kommunikation', 'sub_department': 'Docs', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'teknisk-skribent', 'title': 'Teknisk skribent', 'department': 'Kommunikation', 'sub_department': 'Docs', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'teknisk-skribent-2', 'title': 'Teknisk skribent', 'department': 'Kommunikation', 'sub_department': 'Docs', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'innehallsskapare', 'title': 'Innehållsskapare', 'department': 'Kommunikation', 'sub_department': 'Marketing', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'marknadsforare', 'title': 'Marknadsförare', 'department': 'Kommunikation', 'sub_department': 'Marketing', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'operativ-chef', 'title': 'Operativ chef (COO)', 'department': 'Ledning', 'sub_department': 'Exec', 'model': 'claude-opus-4-8', 'lead': True, 'active': True},
    {'slug': 'produktdirektor', 'title': 'Produktdirektör (CPO)', 'department': 'Ledning', 'sub_department': 'Exec', 'model': 'claude-opus-4-8', 'lead': True, 'active': False},
    {'slug': 'stabschef', 'title': 'Stabschef', 'department': 'Ledning', 'sub_department': 'Exec', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'strategichef', 'title': 'Strategichef', 'department': 'Ledning', 'sub_department': 'Exec', 'model': 'claude-opus-4-8', 'lead': True, 'active': False},
    {'slug': 'teknisk-direktor', 'title': 'Teknisk direktör (CTO)', 'department': 'Ledning', 'sub_department': 'Exec', 'model': 'claude-opus-4-8', 'lead': True, 'active': False},
    {'slug': 'kulturansvarig', 'title': 'Kulturansvarig', 'department': 'People', 'sub_department': 'Culture', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'kompetensutvecklare', 'title': 'Kompetensutvecklare (L&D)', 'department': 'People', 'sub_department': 'L&D', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'kompetensutvecklare-2', 'title': 'Kompetensutvecklare', 'department': 'People', 'sub_department': 'L&D', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'hr-chef', 'title': 'HR-chef (CHRO)', 'department': 'People', 'sub_department': 'Talent', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'rekryterare', 'title': 'Rekryterare', 'department': 'People', 'sub_department': 'Talent', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'rekryterare-2', 'title': 'Rekryterare', 'department': 'People', 'sub_department': 'Talent', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'build-ingenjor', 'title': 'Build-ingenjör', 'department': 'Platform', 'sub_department': 'DevEx', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'devex-ingenjor', 'title': 'Developer-Experience-ingenjör', 'department': 'Platform', 'sub_department': 'DevEx', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'devops-ingenjor-2', 'title': 'DevOps-ingenjör', 'department': 'Platform', 'sub_department': 'DevOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'plattformschef', 'title': 'Plattformschef', 'department': 'Platform', 'sub_department': 'Infra', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'plattformsingenjor', 'title': 'Plattformsingenjör', 'department': 'Platform', 'sub_department': 'Infra', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'plattformsingenjor-2', 'title': 'Plattformsingenjör', 'department': 'Platform', 'sub_department': 'Infra', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'losningsarkitekt', 'title': 'Lösningsarkitekt', 'department': 'Produkt', 'sub_department': 'Arkitektur', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': True},
    {'slug': 'interaktionsdesigner', 'title': 'Interaktionsdesigner', 'department': 'Produkt', 'sub_department': 'Design', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'ux-designer', 'title': 'UX-designer', 'department': 'Produkt', 'sub_department': 'Design', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'ux-lead', 'title': 'UX-lead', 'department': 'Produkt', 'sub_department': 'Design', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'ux-researcher', 'title': 'UX-researcher', 'department': 'Produkt', 'sub_department': 'Design', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'produktchef', 'title': 'Produktchef', 'department': 'Produkt', 'sub_department': 'PM', 'model': 'claude-haiku-4-5', 'lead': True, 'active': True},
    {'slug': 'produktledare-core', 'title': 'Produktledare CNS-core', 'department': 'Produkt', 'sub_department': 'PM', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'produktledare-dashboard', 'title': 'Produktledare Dashboard', 'department': 'Produkt', 'sub_department': 'PM', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'produktledare-mcp', 'title': 'Produktledare MCP-plattform', 'department': 'Produkt', 'sub_department': 'PM', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'produktledare-tui', 'title': 'Produktledare TUI', 'department': 'Produkt', 'sub_department': 'PM', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'product-ops', 'title': 'Product Ops', 'department': 'Produkt', 'sub_department': 'ProductOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'produktanalytiker', 'title': 'Produktanalytiker', 'department': 'Produkt', 'sub_department': 'ProductOps', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'sessionskoordinator', 'title': 'Sessionskoordinator', 'department': 'Program', 'sub_department': 'Coordination', 'model': 'claude-haiku-4-5', 'lead': False, 'active': True},
    {'slug': 'sessionskoordinator-2', 'title': 'Sessionskoordinator', 'department': 'Program', 'sub_department': 'Coordination', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'programledare', 'title': 'Programledare', 'department': 'Program', 'sub_department': 'Delivery', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'scrum-master', 'title': 'Scrum Master', 'department': 'Program', 'sub_department': 'Delivery', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'scrum-master-2', 'title': 'Scrum Master', 'department': 'Program', 'sub_department': 'Delivery', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'leveranschef', 'title': 'Leveranschef', 'department': 'Program', 'sub_department': 'Release', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'release-koordinator', 'title': 'Release-koordinator', 'department': 'Program', 'sub_department': 'Release', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
    {'slug': 'datavetare', 'title': 'Datavetare', 'department': 'R&D', 'sub_department': 'Innovation', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'innovationsledare', 'title': 'Innovationsledare', 'department': 'R&D', 'sub_department': 'Innovation', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': False},
    {'slug': 'prototypare', 'title': 'Prototypare', 'department': 'R&D', 'sub_department': 'Innovation', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'forskningsledare', 'title': 'Forskningsledare', 'department': 'R&D', 'sub_department': 'Research', 'model': 'claude-sonnet-4-6', 'lead': True, 'active': True},
    {'slug': 'konkurrentanalytiker', 'title': 'Konkurrentanalytiker', 'department': 'R&D', 'sub_department': 'Research', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'marknadsanalytiker', 'title': 'Marknadsanalytiker', 'department': 'R&D', 'sub_department': 'Research', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'teknikspanare', 'title': 'Teknikspanare', 'department': 'R&D', 'sub_department': 'Research', 'model': 'claude-sonnet-4-6', 'lead': False, 'active': False},
    {'slug': 'webbresearcher', 'title': 'Webbresearcher', 'department': 'R&D', 'sub_department': 'Research', 'model': 'claude-haiku-4-5', 'lead': False, 'active': False},
]
